{% set name = "wagtail-import-export-tool" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail-import-export-tool-{{ version }}.tar.gz
  sha256: 2b574b1cf40bce45476a6ec08c23fce91a696074e966940168a215bb6bfaa4e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=5.0

test:
  imports:
    - wagtailimportexport
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/berkalpyakici/wagtail-import-export-tool
  summary: Import/Export tool for Wagtail CMS (built on top of Django), that supports pages, images, documents, and snippets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
